
package webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 4.0.0-M4
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "controllerWS", targetNamespace = "http://webServices/", wsdlLocation = "http://192.168.1.8:9125/controllerWS?wsdl")
public class ControllerWS_Service
    extends Service
{

    private final static URL CONTROLLERWS_WSDL_LOCATION;
    private final static WebServiceException CONTROLLERWS_EXCEPTION;
    private final static QName CONTROLLERWS_QNAME = new QName("http://webServices/", "controllerWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.1.8:9125/controllerWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONTROLLERWS_WSDL_LOCATION = url;
        CONTROLLERWS_EXCEPTION = e;
    }

    public ControllerWS_Service() {
        super(__getWsdlLocation(), CONTROLLERWS_QNAME);
    }

    public ControllerWS_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONTROLLERWS_QNAME, features);
    }

    public ControllerWS_Service(URL wsdlLocation) {
        super(wsdlLocation, CONTROLLERWS_QNAME);
    }

    public ControllerWS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONTROLLERWS_QNAME, features);
    }

    public ControllerWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ControllerWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ControllerWS
     */
    @WebEndpoint(name = "controllerWSPort")
    public ControllerWS getControllerWSPort() {
        return super.getPort(new QName("http://webServices/", "controllerWSPort"), ControllerWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ControllerWS
     */
    @WebEndpoint(name = "controllerWSPort")
    public ControllerWS getControllerWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webServices/", "controllerWSPort"), ControllerWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONTROLLERWS_EXCEPTION!= null) {
            throw CONTROLLERWS_EXCEPTION;
        }
        return CONTROLLERWS_WSDL_LOCATION;
    }

}
