
package webservices;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 4.0.0-M4
 * Generated source version: 3.0
 * 
 */
@WebService(name = "controllerWS", targetNamespace = "http://webServices/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ControllerWS {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "existeUsuario", targetNamespace = "http://webServices/", className = "webservices.ExisteUsuario")
    @ResponseWrapper(localName = "existeUsuarioResponse", targetNamespace = "http://webServices/", className = "webservices.ExisteUsuarioResponse")
    @Action(input = "http://webServices/controllerWS/existeUsuarioRequest", output = "http://webServices/controllerWS/existeUsuarioResponse")
    public boolean existeUsuario(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://webServices/", className = "webservices.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://webServices/", className = "webservices.LoginResponse")
    @Action(input = "http://webServices/controllerWS/loginRequest", output = "http://webServices/controllerWS/loginResponse")
    public boolean login(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isProponente", targetNamespace = "http://webServices/", className = "webservices.IsProponente")
    @ResponseWrapper(localName = "isProponenteResponse", targetNamespace = "http://webServices/", className = "webservices.IsProponenteResponse")
    @Action(input = "http://webServices/controllerWS/isProponenteRequest", output = "http://webServices/controllerWS/isProponenteResponse")
    public boolean isProponente(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getImg", targetNamespace = "http://webServices/", className = "webservices.GetImg")
    @ResponseWrapper(localName = "getImgResponse", targetNamespace = "http://webServices/", className = "webservices.GetImgResponse")
    @Action(input = "http://webServices/controllerWS/getImgRequest", output = "http://webServices/controllerWS/getImgResponse")
    public byte[] getImg(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "emailUsado", targetNamespace = "http://webServices/", className = "webservices.EmailUsado")
    @ResponseWrapper(localName = "emailUsadoResponse", targetNamespace = "http://webServices/", className = "webservices.EmailUsadoResponse")
    @Action(input = "http://webServices/controllerWS/emailUsadoRequest", output = "http://webServices/controllerWS/emailUsadoResponse")
    public boolean emailUsado(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "existe", targetNamespace = "http://webServices/", className = "webservices.Existe")
    @ResponseWrapper(localName = "existeResponse", targetNamespace = "http://webServices/", className = "webservices.ExisteResponse")
    @Action(input = "http://webServices/controllerWS/existeRequest", output = "http://webServices/controllerWS/existeResponse")
    public boolean existe(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<webservices.DtoUsuario>
     */
    @WebMethod(operationName = "ListaDTOUsuarios")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ListaDTOUsuarios", targetNamespace = "http://webServices/", className = "webservices.ListaDTOUsuarios")
    @ResponseWrapper(localName = "ListaDTOUsuariosResponse", targetNamespace = "http://webServices/", className = "webservices.ListaDTOUsuariosResponse")
    @Action(input = "http://webServices/controllerWS/ListaDTOUsuariosRequest", output = "http://webServices/controllerWS/ListaDTOUsuariosResponse")
    public List<DtoUsuario> listaDTOUsuarios();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<webservices.DtoUsuario>
     */
    @WebMethod(operationName = "Seguidos")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Seguidos", targetNamespace = "http://webServices/", className = "webservices.Seguidos")
    @ResponseWrapper(localName = "SeguidosResponse", targetNamespace = "http://webServices/", className = "webservices.SeguidosResponse")
    @Action(input = "http://webServices/controllerWS/SeguidosRequest", output = "http://webServices/controllerWS/SeguidosResponse")
    public List<DtoUsuario> seguidos(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sigueAUsuario", targetNamespace = "http://webServices/", className = "webservices.SigueAUsuario")
    @ResponseWrapper(localName = "sigueAUsuarioResponse", targetNamespace = "http://webServices/", className = "webservices.SigueAUsuarioResponse")
    @Action(input = "http://webServices/controllerWS/sigueAUsuarioRequest", output = "http://webServices/controllerWS/sigueAUsuarioResponse")
    public boolean sigueAUsuario(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "seguir", targetNamespace = "http://webServices/", className = "webservices.Seguir")
    @ResponseWrapper(localName = "seguirResponse", targetNamespace = "http://webServices/", className = "webservices.SeguirResponse")
    @Action(input = "http://webServices/controllerWS/seguirRequest", output = "http://webServices/controllerWS/seguirResponse")
    public boolean seguir(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "unFollowUser", targetNamespace = "http://webServices/", className = "webservices.UnFollowUser")
    @ResponseWrapper(localName = "unFollowUserResponse", targetNamespace = "http://webServices/", className = "webservices.UnFollowUserResponse")
    @Action(input = "http://webServices/controllerWS/unFollowUserRequest", output = "http://webServices/controllerWS/unFollowUserResponse")
    public boolean unFollowUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg10
     * @param arg11
     * @param arg7
     * @param arg6
     * @param arg9
     * @param arg8
     */
    @WebMethod
    @RequestWrapper(localName = "registroUsuario", targetNamespace = "http://webServices/", className = "webservices.RegistroUsuario")
    @ResponseWrapper(localName = "registroUsuarioResponse", targetNamespace = "http://webServices/", className = "webservices.RegistroUsuarioResponse")
    @Action(input = "http://webServices/controllerWS/registroUsuarioRequest", output = "http://webServices/controllerWS/registroUsuarioResponse")
    public void registroUsuario(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        byte[] arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        String arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        boolean arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        String arg9,
        @WebParam(name = "arg10", targetNamespace = "")
        String arg10,
        @WebParam(name = "arg11", targetNamespace = "")
        String arg11);

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.DtoProponente
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDTOProponente", targetNamespace = "http://webServices/", className = "webservices.GetDTOProponente")
    @ResponseWrapper(localName = "getDTOProponenteResponse", targetNamespace = "http://webServices/", className = "webservices.GetDTOProponenteResponse")
    @Action(input = "http://webServices/controllerWS/getDTOProponenteRequest", output = "http://webServices/controllerWS/getDTOProponenteResponse")
    public DtoProponente getDTOProponente(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.DtoColaborador
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDTOColaborador", targetNamespace = "http://webServices/", className = "webservices.GetDTOColaborador")
    @ResponseWrapper(localName = "getDTOColaboradorResponse", targetNamespace = "http://webServices/", className = "webservices.GetDTOColaboradorResponse")
    @Action(input = "http://webServices/controllerWS/getDTOColaboradorRequest", output = "http://webServices/controllerWS/getDTOColaboradorResponse")
    public DtoColaborador getDTOColaborador(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod(operationName = "CancelarColaboracion")
    @RequestWrapper(localName = "CancelarColaboracion", targetNamespace = "http://webServices/", className = "webservices.CancelarColaboracion")
    @ResponseWrapper(localName = "CancelarColaboracionResponse", targetNamespace = "http://webServices/", className = "webservices.CancelarColaboracionResponse")
    @Action(input = "http://webServices/controllerWS/CancelarColaboracionRequest", output = "http://webServices/controllerWS/CancelarColaboracionResponse")
    public void cancelarColaboracion(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<webservices.DtoUsuario>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSeguidores", targetNamespace = "http://webServices/", className = "webservices.GetSeguidores")
    @ResponseWrapper(localName = "getSeguidoresResponse", targetNamespace = "http://webServices/", className = "webservices.GetSeguidoresResponse")
    @Action(input = "http://webServices/controllerWS/getSeguidoresRequest", output = "http://webServices/controllerWS/getSeguidoresResponse")
    public List<DtoUsuario> getSeguidores(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<webservices.DtoUsuario>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "rankingUsuarios", targetNamespace = "http://webServices/", className = "webservices.RankingUsuarios")
    @ResponseWrapper(localName = "rankingUsuariosResponse", targetNamespace = "http://webServices/", className = "webservices.RankingUsuariosResponse")
    @Action(input = "http://webServices/controllerWS/rankingUsuariosRequest", output = "http://webServices/controllerWS/rankingUsuariosResponse")
    public List<DtoUsuario> rankingUsuarios();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<webservices.DtoPropuesta>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFavoritas", targetNamespace = "http://webServices/", className = "webservices.GetFavoritas")
    @ResponseWrapper(localName = "getFavoritasResponse", targetNamespace = "http://webServices/", className = "webservices.GetFavoritasResponse")
    @Action(input = "http://webServices/controllerWS/getFavoritasRequest", output = "http://webServices/controllerWS/getFavoritasResponse")
    public List<DtoPropuesta> getFavoritas(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<webservices.DtoPropuesta>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPropuestasCreadasPorProponente", targetNamespace = "http://webServices/", className = "webservices.GetPropuestasCreadasPorProponente")
    @ResponseWrapper(localName = "getPropuestasCreadasPorProponenteResponse", targetNamespace = "http://webServices/", className = "webservices.GetPropuestasCreadasPorProponenteResponse")
    @Action(input = "http://webServices/controllerWS/getPropuestasCreadasPorProponenteRequest", output = "http://webServices/controllerWS/getPropuestasCreadasPorProponenteResponse")
    public List<DtoPropuesta> getPropuestasCreadasPorProponente(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<webservices.DtoColaboracion>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "colaboraciones", targetNamespace = "http://webServices/", className = "webservices.Colaboraciones")
    @ResponseWrapper(localName = "colaboracionesResponse", targetNamespace = "http://webServices/", className = "webservices.ColaboracionesResponse")
    @Action(input = "http://webServices/controllerWS/colaboracionesRequest", output = "http://webServices/controllerWS/colaboracionesResponse")
    public List<DtoColaboracion> colaboraciones(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg10
     * @param arg11
     * @param arg7
     * @param arg6
     * @param arg9
     * @param arg8
     */
    @WebMethod
    @RequestWrapper(localName = "altaPropuesta", targetNamespace = "http://webServices/", className = "webservices.AltaPropuesta")
    @ResponseWrapper(localName = "altaPropuestaResponse", targetNamespace = "http://webServices/", className = "webservices.AltaPropuestaResponse")
    @Action(input = "http://webServices/controllerWS/altaPropuestaRequest", output = "http://webServices/controllerWS/altaPropuestaResponse")
    public void altaPropuesta(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        int arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        int arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        String arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        List<TipoRetorno> arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        String arg9,
        @WebParam(name = "arg10", targetNamespace = "")
        String arg10,
        @WebParam(name = "arg11", targetNamespace = "")
        Estado arg11);

    /**
     * 
     * @return
     *     returns java.util.List<webservices.DtoCategoria>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCategorias", targetNamespace = "http://webServices/", className = "webservices.GetCategorias")
    @ResponseWrapper(localName = "getCategoriasResponse", targetNamespace = "http://webServices/", className = "webservices.GetCategoriasResponse")
    @Action(input = "http://webServices/controllerWS/getCategoriasRequest", output = "http://webServices/controllerWS/getCategoriasResponse")
    public List<DtoCategoria> getCategorias();

    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hello", targetNamespace = "http://webServices/", className = "webservices.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://webServices/", className = "webservices.HelloResponse")
    @Action(input = "http://webServices/controllerWS/helloRequest", output = "http://webServices/controllerWS/helloResponse")
    public String hello(
        @WebParam(name = "name", targetNamespace = "")
        String name);

}
