
package webservices;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 4.0.0-M4
 * Generated source version: 3.0
 * 
 */
@WebService(name = "controllerWS", targetNamespace = "http://webServices/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ControllerWS {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "existe", targetNamespace = "http://webServices/", className = "webservices.Existe")
    @ResponseWrapper(localName = "existeResponse", targetNamespace = "http://webServices/", className = "webservices.ExisteResponse")
    @Action(input = "http://webServices/controllerWS/existeRequest", output = "http://webServices/controllerWS/existeResponse")
    public boolean existe(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hello", targetNamespace = "http://webServices/", className = "webservices.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://webServices/", className = "webservices.HelloResponse")
    @Action(input = "http://webServices/controllerWS/helloRequest", output = "http://webServices/controllerWS/helloResponse")
    public String hello(
        @WebParam(name = "name", targetNamespace = "")
        String name);

}
